### ISSUE TITLE
Inserting of first code version of rotseutil code

### ISSUE THREAD

**Issue by rkehoe** [rotsehub/rotseutil#1]
Hello @gdhungana, @danielsela42, @rstaten I am looking thru rotsehub and see that the repos do not yet have code in them.  I suspect this is because the code is in private repos and branches.  

Let’s move code into rotseutil and ImageDiff first.  Please place whatever code you have into these repos and we can then go from there.

I’ll leave this Issue open until we get to that milestone.

**Comment by rkehoe** [comment]
@rkehoe This is a pointer to the rotseutil wiki

**Comment by danielsela42** [comment]
Hello @rkehoe. I have the rotseutil ready to upload it does need some edits on the documentation, but I should still be able to add it to the repository. I believe I would have to add it to the master branch though, would that be fine?

**Comment by gdhungana** [comment]
@rkehoe, I have made some changes and made some commits
- renamed rosteutil --> rotseutil
- added a README, .gitignore and LICENSE file 
- added a folder datautil/scripts and put the M2 data structure management code there; albeit that is also in rotsedatamodel repo( which is where that likely should be)

I think we can put utility functions related to data and analysis here. For the development of specific projects, we can rely on this repo, but this repo would ideally not rely on them. So this can serve as a dependent general library for other projects. 

@danielsela42 Please clone this master, create a new branch, and put your work on the existing directory or a new one and push the branch here. We can review and shuffle their places based on scope.

**Comment by rkehoe** [comment]
@gdhungana @rstaten I am looking at old Issues and trying to close those off that are either done or no longer relevant due to subsequent activity.  Can you both take a look at this Issue and comment on what the status is, and whether Ic an close this Issue?

**Comment by rkehoe** [comment]
@gdhungana Just pinging you that I am closing this, in case there was something unresolved you want to bring up in our meeting next.
